const dbCards = {
  mozaika: [
    {
      id: 1,
      long: 1,
      cost: 1999,
      currency: "₽",
      type: "соло",
      frost: "* Без заморозки",
    },
    {
      id: 2,
      long: 6,
      cost: 9900,
      currency: "₽",
      type: "соло",
      frost: "* Без заморозки",
    },
    {
      id: 3,
      long: 9,
      cost: 13900,
      currency: "₽",
      type: "соло",
      frost: "* Без заморозки",
    },
    {
      id: 4,
      long: 12,
      cost: 9900,
      currency: "₽",
      type: "дневная",
      frost: "* 1 месяц заморозки",
    },
    {
      id: 5,
      long: 12,
      cost: 19900,
      currency: "₽",
      type: "соло",
      frost: "* 1 месяц заморозки",
    },
  ],
  schelkovo: [
    {
      id: 1,
      long: 1,
      cost: 2999,
      currency: "₽",
      type: "соло",
      frost: "* Без заморозки",
    },
    {
      id: 2,
      long: 6,
      cost: 14990,
      currency: "₽",
      type: "соло",
      frost: "* Без заморозки",
    },
    {
      id: 3,
      long: 9,
      cost: 21990,
      currency: "₽",
      type: "соло",
      frost: "* Без заморозки",
    },
    {
      id: 4,
      long: 12,
      cost: 14990,
      currency: "₽",
      type: "дневная",
      frost: "* 1 месяц заморозки",
    },
    {
      id: 5,
      long: 12,
      cost: 24990,
      currency: "₽",
      type: "соло",
      frost: "* 1 месяц заморозки",
    },
  ],
};

export default dbCards;
